tasks:
  - name: interface-tiktok
    init: |
      cd /workspace/interface-tiktok 
      nvm install node
      npm install -g npm@latest
    command: |
      cd /workspace/interface-tiktok
      echo "workshop-astra-tik-tok gitpod ready - LET'S DO THIS!"
      npm install
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore    
